[libdefaults]
    default_realm = LAB.EXAMPLE
    rdns = false
    forwardable = true

[realms]
    LAB.EXAMPLE = {
        kdc = testserver1.lab.example
        admin_server = testserver1.lab.example
    }

[domain_realm]
    .lab.example = LAB.EXAMPLE
    lab.example = LAB.EXAMPLE
